### ISSUE TITLE
XML vs functions

### ISSUE THREAD

**Issue by rjmk** [choojs/hyperx#17]
Perhaps a strange place to put this issue, but was wondering why one would prefer the JSX/hyperx/XML API to just using the constructor functions. Do people find it easier to maintain / read / refactor?  
I find I pass whole objects around as props in react so often that I'm pretty reliant on spread. I'd rather just pass the object to a function.

**Comment by tbranyen** [comment]
I've been thinking about this too, and I think it comes down to liking HTML. Many of us learned web development starting with HTML and it's a building block of the web. Ignoring it and only focusing on JS is fine for some, but not for all.

I think it'd be fine to augment the tagged helper to support spreading objects as properties into an element.

Something like this:

``` javascript
const props = { id: 'cool' }

hyperx`
  <div ${props}></div>
`
```

**Comment by JamesKyburz** [comment]
This is already supported but maybe only documented in [this test].

It was implemented by [this pr].

```javascript
var hyperx = require('hyperx')
var vdom = require('virtual-dom')
var hx = hyperx(vdom.h)
const props = { id: 'cool' }

var el = hx`
  <div ${props}></div>
`
console.log(vdom.create(el).toString()) // <div id="cool"></div>
```
[this pr]:https://github.com/substack/hyperx/pull/16
[this test]:https://github.com/substack/hyperx/blob/master/test/key.js#L46
