### ISSUE TITLE
Breaks When Using <br/>

### ISSUE THREAD

**Issue by dodekeract** [choojs/hyperx#38]
I tried to modify [hyperapp](https://github.com/hyperapp/hyperapp)'s `counter` example. When inserting a line-break `<br/>` it broke. 🙁

## Console

```javascript
InvalidCharacterError (DOM Exception 5): The string contains invalid characters.
```

## Minimal Repro

```javascript
app({
    view: () => html`<div>a<br/>b</div>`
})
```

## Meta

Corresponding [issue on hyperapp's repo](https://github.com/hyperapp/hyperapp/issues/7).  
Related to substack/hyperx#34.

---

*Note that I do realize that `<br>` works. `<br/>` is more explicit though and as a React-user I'd like to keep this pattern.*

**Comment by Ramblurr** [comment]
I also was caught by this bug.

**Comment by josephg** [comment]
Some notes:

- Self-closing tags don't exist in the html spec.
- Browsers do ignore the '/' and treat `<br/>` and `<br>` as synonyms
- Hyperx works fine if you put in a space - `<br />`
- It should be easy to change the parser to support this. Its probably a ~2 line change to stop parsing the tag name when the parser sees a '/' character. Make a unit test, fix the code and submit a PR.
- For now, the workaround is to write `<br />`

**Comment by yoshuawuyts** [comment]
A PR to support `<br/>` would be very welcome!
