### ISSUE TITLE
react: key warnings

### ISSUE THREAD

**Issue by dereke** [choojs/hyperx#43]
I seem to be getting a lot of key warnings when using hyperx with react. Here is an example that generates a key warning but shouldn't really:

```js
const React = require('react')
const hyperx = require('hyperx')
const hx = hyperx(React.createElement)

hx`<div><a href="#">link</a></div>`
```

If I add a key to the anchor tag the warning goes away - but I shouldn't really need to do that.

Any solutions to this?

**Comment by dereke** [comment]
I've done a bit more research on this. When you have this JSX:
```jsx
<div><a href="#">link</a></div>
```
it will output this JS:

```js
  return React.createElement(
    "div",
    null,
    React.createElement(
      "a",
      { href: "#" },
      "link"
    )
  );
```

The example I gave above:
```js
hx`<div><a href="#">link</a></div>`
```
Produces this JS:

```js
  return React.createElement(
    "div",
    null,
    [
      React.createElement(
        "a",
        { href: "#" },
        "link"
      )
    ]
  );
```

Note the last parameter is an array rather than an element. `React.createElement` can take either an array of elements as the last parameter or a spread of elements. When an array is supplied it warns that you should add `key` properties to uniquely identify them.

Hyperx seems to create arrays rather than spreading the children which is why we get key warnings.

**Comment by AlecRust** [comment]
Any ideas on this? Is anyone using hyperx without all these React warnings?

**Comment by s9k** [comment]
```js
function createElement(Component, props, children) {
    return React.createElement(Component, props, ...children);
}

const hx = hyperx(createElement);
```

**Comment by goto-bus-stop** [comment]
i think @s9k's solution is the best way to go. documentation patch welcome!
