### ISSUE TITLE
Rollup

### ISSUE THREAD

**Issue by rbiggs** [choojs/hyperx#54]
I use Rollup to bundle my code. I use it so I can organize a project's code as ES6 modules. I can't seem to find a way to import Hyperx with Rollup. I've successfully used other NPM modules with Rollup, so I'm assuming its something about how hyperx is getting exported. 
I'd like to be able to do the following:
```javascript
import {hyperx} from  'hyperx'
const html = hyperx(h)
// etc
```
But I'm not having any luck. 
I am using rollup-plugin-commonjs with rollup, so that's not the issue:
```javascript
commonjs({
  include: 'node_modules/**'
})
```
But when I build, I get this error in the console:
```
Error: 'hyperx' is not exported by node_modules/hyperx/index.js
```
Any idea how to be able to use hyperx with Rollup like a normal ES6 module?

**Comment by yoshuawuyts** [comment]
Hmm, I haven't used Rollup with Choo, but given that we only ever expose
commonJS modules, perhaps
https://github.com/rollup/rollup-plugin-commonjs would
be the right solution?

**Comment by rbiggs** [comment]
Actually, I am using `rollup-plugin-commonjs` and usually it just works for commonjs modules. I'll take another look at my setup after a couple of ☕️☕️

**Comment by slaskis** [comment]
Have you tried using the default export? It looks to me like hyperx is using `module.export` and not `exports.hyperx`.

```
import hyperx from  'hyperx'
```

**Comment by rbiggs** [comment]
Yup. Tried that and got:
```
Error: 'default' is not exported by node_modules/hyperx/index.js
```

**Comment by styfle** [comment]
Did you try

```js
import * as hyperx from 'hyperx';
```

**Comment by rbiggs** [comment]
With
```javascript
import * as hyperx from 'hyperx'
```
I get:
```
Error: Cannot call a namespace ('hyperx')
```

**Comment by rbiggs** [comment]
Finally found the solution, thanks to a thread by Rich Harris on Gitlab. For Rollup to be able to import and bundle hyperx with other ES6 module imports you need to have the `rollup-plugin-commonjs` configured like this. Notice the `ignoreGlobal: true` part.

```javascript
commonjs({
  include: 'node_modules/**',
  ignoreGlobal: true
})
```
Maybe you guys should put something in your docs about using Hyperx with Rollup for other people using it with ES6 imports so they don't go through what I just did.
