### ISSUE TITLE
Allow custom attrToProp function

### ISSUE THREAD

**Issue by Siilwyn** [choojs/hyperx#78]
Would it be a good idea to allow `attrToProp` to accept a function? That way as a user I can transform the needed attributes. I'm mainly asking this because the `hyperscript-attribute-to-property` dependency is missing basic attributes like `srcset` & [seems unmaintained](https://github.com/feross/hyperscript-attribute-to-property/pull/9). Secondly it does not include SVG attributes like `stroke-linecap` which in my case are used directly in the templating.

**Comment by feross** [comment]
Just wanted to note that `hyperscript-attribute-to-property` is maintained.
