### ISSUE TITLE
Can I become a maintainer on this project?

### ISSUE THREAD

**Issue by mreinstein** [choojs/hyperx#83]
I'd like to do a major release for hyperx: 
* several fixes for open parsing bugs.
  * #41
  * #82
* optionally consider adopting es6-isms (let, const, etc.)
* optionally consider es modules since all LTS node versions and most browsers have support now

@substack @goto-bus-stop  is this something you'd be interested in? This module underpins a lot of stuff for projects I work on and being able to fix some of the bit rot would be nice, so I don't have to maintain my own fork, and others could benefit too.

**Comment by mreinstein** [comment]
I'd like to consider refactoring `parse(str)` to be an explicit state machine.   Rather than having very long `if`/`else if` chains we could have a separate function for each state, something like this:

```javascript
function open (c, m) { … }

function attr_key (c, m) { … }

var lookup = {
  OPEN: open,
  ATTR_KEY: attr_key,
  ⋮
}

function parse (str) {
    var i, machine = {
         state: TEXT,
         res: [ ],
         reg: ''
    }

    for (i=0; i < str.length; i++)
      lookup[machine.state](str[i], machine)

    return machine.res
}
```

**Comment by rook2pawn** [comment]
Just ran into the #41 issue .. @goto-bus-stop @mreinstein I'd also like to volunteer to help maintain.

**Comment by mreinstein** [comment]
I would love someone to take over ownership of this project but sadly it is a mausoleum.

**Comment by mreinstein** [comment]
This fork has my latest https://github.com/mreinstein/hyperx

**Comment by mreinstein** [comment]
@goto-bus-stop @substack I'm still keen to maintain this project.  Any chance of letting me do this? I use `hyperx` in my work and personal projects and I'm really not crazy about maintaining these personal forks if I can avoid it.

**Comment by goto-bus-stop** [comment]
@mreinstein thanks for the interest 😸 I sent an invitation to the GitHub org. I can't invite to npm on my phone I think but I can do that later.

**Comment by mreinstein** [comment]
Nice!  My username on npm is mreinstein.

I'm assuming you're too busy with other things to maintain this, but if
you'd like I'm happy to include you on PRs/activity stuff.  My immediate
plans are to take the changes in my fork and get them published into
choojs/hyperx

thanks again!

-Michael

**Comment by goto-bus-stop** [comment]
Yeah I can't realistically commit to doing reviews. feel free to request them especially if you do need input on things, but I'm not actively using these projects at the moment so I think my opinions on direction are not the most important, and I may not find time/motivation to do much anyways 🙂
